services:
  cocoda:
    image: ghcr.io/gbv/cocoda:1
    volumes:
      - ./data/cocoda:/config
    ports:
      # Use host port 30100
      - 30100:80
    restart: unless-stopped

  jskos-server:
    image: ghcr.io/gbv/jskos-server:2
    depends_on:
      - db
    volumes:
      - ./data/jskos-server:/config
    # environment:
    #   - NODE_ENV=production # note that this requires the server to be run behind a HTTPS proxy
    ports:
      - 30101:3000
    restart: unless-stopped

  login-server:
    image: ghcr.io/gbv/login-server:0.8
    depends_on:
      - db
    volumes:
      - ./data/login-server:/config
      # - ./data/login-server-static:/usr/src/app/static # if required
    environment:
      - MONGO_HOST=db
      - BASE_URL=http://localhost:30104/
      - ALLOWED_ORIGINS=http://localhost:30100
    ports:
      - 30104:3004
    restart: unless-stopped

  mongo:
    image: mongo:7
    # replace this with your UID/GID if necessary (id -u; id -g); remove on macOS/Windows
    user: 1000:1000
    volumes:
      - ./data/db:/data/db
    # command: su -c "mongod --bind_ip_all" root # recommended if run under Rootless Docker (as it will map the volume files to your UID instead of a subordinate UID)
    restart: unless-stopped
